---
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/server/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Stockholm"
    labels:
      - "Lights On"
      - "Dependencies"
    reviewers:
      - "iZettle/developer-experience-devs"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Stockholm"
    labels:
      - "Lights On"
      - "Dependencies"
    reviewers:
      - "iZettle/developer-experience-devs"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Stockholm"
    labels:
      - "Lights On"
      - "Dependencies"
    reviewers:
      - "iZettle/developer-experience-devs"

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Stockholm"
    labels:
      - "Lights On"
      - "Dependencies"
    reviewers:
      - "iZettle/developer-experience-devs"
